wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683013452.066123
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.9.7
      5: 0.14.2
      8:
      - 5
model_name:
  desc: null
  value: predrnn_v2
opt:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 1
